import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navigation/header";
import SmoothScrollProvider from "@/components/layout/navigation/ReactLenis";
import Footer from "@/components/layout/navigation/footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-poppins antialiased overflow-x-hidden`}
      >
        {/* Navigation with dropdown support */}
        <Navbar />

        {/* Main content area */}
        <main className="relative">
          <SmoothScrollProvider>{children}</SmoothScrollProvider>
        </main>
        <Footer />
      </body>
    </html>
  );
}